openapi: 3.1.0
info:
  title: Businesses API
  version: 1.0.0
  description: API for managing businesses (tenants).
paths:
  /api/businesses:
    get:
      summary: Get all businesses
      description: Get all businesses, optionally filtered by active status.
      security:
        - bearerAuth: []
      parameters:
        - name: active
          in: query
          description: Filter by active status (true to show only active)
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of businesses
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Business'
    post:
      summary: Create a new business
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - code
              properties:
                name:
                  type: string
                  description: The display name of the business
                code:
                  type: string
                  description: The URL-friendly slug/code for the business
      responses:
        '201':
          description: Business created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
        '400':
          description: Bad request (missing fields)
        '409':
          description: Business with this code or name already exists
  /api/businesses/{business_id}:
    parameters:
      - name: business_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get a business by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
        '404':
          description: Business not found
    put:
      summary: Update a business
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
                is_active:
                  type: boolean
      responses:
        '200':
          description: Business updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
        '404':
          description: Business not found
        '409':
          description: Business with this code or name already exists
    delete:
      summary: Deactivate a business (soft delete)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business deactivated
          content:
             application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Business not found
components:
  schemas:
    Business:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        code:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login endpoint
