openapi: 3.1.0
info:
  title: Businesses API
  version: 1.0.0
  description: API for managing businesses (multi-tenancy entities).
paths:
  /api/businesses:
    get:
      summary: Get all businesses
      description: Get all businesses. For regular users, only returns their own business.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of businesses
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Business'
        '404':
          description: Business not found
    post:
      summary: Create a new business
      description: Create a new business. In production, this should be restricted to super admins.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - business_name
              properties:
                business_name:
                  type: string
                business_code:
                  type: string
      responses:
        '201':
          description: Business created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
        '409':
          description: Business with this name or code already exists
  /api/businesses/{business_id}:
    parameters:
      - name: business_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get a business by ID
      description: Get a specific business by ID. Users can only access their own business.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
        '403':
          description: Access denied
        '404':
          description: Business not found
    put:
      summary: Update a business
      description: Update a business. Users can only update their own business.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                business_name:
                  type: string
                business_code:
                  type: string
                is_active:
                  type: boolean
      responses:
        '200':
          description: Business updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
        '403':
          description: Access denied
        '404':
          description: Business not found
        '409':
          description: Conflict (e.g. name or code already exists)
    delete:
      summary: Delete (deactivate) a business
      description: Soft delete a business by deactivating it.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business deactivated
        '403':
          description: Access denied
        '404':
          description: Business not found
  /api/businesses/{business_id}/activate:
    parameters:
      - name: business_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Activate a business
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business activated
        '404':
          description: Business not found
  /api/businesses/{business_id}/deactivate:
    parameters:
      - name: business_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Deactivate a business
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business deactivated
        '404':
          description: Business not found
components:
  schemas:
    Business:
      type: object
      properties:
        id:
          type: string
          format: uuid
        business_name:
          type: string
        business_code:
          type: string
          nullable: true
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login endpoint
