openapi: 3.1.0
info:
  title: Businesses API
  version: 1.0.0
<<<<<<< HEAD
  description: API for managing businesses (tenants).
=======
  description: API for managing businesses (multi-tenancy entities).
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
paths:
  /api/businesses:
    get:
      summary: Get all businesses
<<<<<<< HEAD
      description: Get all businesses, optionally filtered by active status.
      security:
        - bearerAuth: []
      parameters:
        - name: active
          in: query
          description: Filter by active status (true to show only active)
          schema:
            type: boolean
            default: false
=======
      description: Get all businesses. For regular users, only returns their own business.
      security:
        - bearerAuth: []
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
      responses:
        '200':
          description: List of businesses
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Business'
<<<<<<< HEAD
    post:
      summary: Create a new business
=======
        '404':
          description: Business not found
    post:
      summary: Create a new business
      description: Create a new business. In production, this should be restricted to super admins.
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
<<<<<<< HEAD
                - name
                - code
              properties:
                name:
                  type: string
                  description: The display name of the business
                code:
                  type: string
                  description: The URL-friendly slug/code for the business
=======
                - business_name
              properties:
                business_name:
                  type: string
                business_code:
                  type: string
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
      responses:
        '201':
          description: Business created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
<<<<<<< HEAD
        '400':
          description: Bad request (missing fields)
        '409':
          description: Business with this code or name already exists
=======
        '409':
          description: Business with this name or code already exists
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
  /api/businesses/{business_id}:
    parameters:
      - name: business_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get a business by ID
<<<<<<< HEAD
=======
      description: Get a specific business by ID. Users can only access their own business.
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
<<<<<<< HEAD
=======
        '403':
          description: Access denied
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
        '404':
          description: Business not found
    put:
      summary: Update a business
<<<<<<< HEAD
=======
      description: Update a business. Users can only update their own business.
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
<<<<<<< HEAD
                name:
                  type: string
                code:
=======
                business_name:
                  type: string
                business_code:
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
                  type: string
                is_active:
                  type: boolean
      responses:
        '200':
          description: Business updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Business'
<<<<<<< HEAD
        '404':
          description: Business not found
        '409':
          description: Business with this code or name already exists
    delete:
      summary: Deactivate a business (soft delete)
=======
        '403':
          description: Access denied
        '404':
          description: Business not found
        '409':
          description: Conflict (e.g. name or code already exists)
    delete:
      summary: Delete (deactivate) a business
      description: Soft delete a business by deactivating it.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business deactivated
        '403':
          description: Access denied
        '404':
          description: Business not found
  /api/businesses/{business_id}/activate:
    parameters:
      - name: business_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Activate a business
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business activated
        '404':
          description: Business not found
  /api/businesses/{business_id}/deactivate:
    parameters:
      - name: business_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Deactivate a business
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Business deactivated
<<<<<<< HEAD
          content:
             application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
=======
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
        '404':
          description: Business not found
components:
  schemas:
    Business:
      type: object
      properties:
        id:
          type: string
          format: uuid
<<<<<<< HEAD
        name:
          type: string
        code:
          type: string
=======
        business_name:
          type: string
        business_code:
          type: string
          nullable: true
>>>>>>> edd1bb21294eae8a7b37e75977dd739df6834c2d
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login endpoint
