openapi: 3.1.0
info:
  title: Sites API
  version: 1.0.0
  description: API for managing sites.
paths:
  /api/sites:
    get:
      summary: Get all sites
      description: Get all sites, optionally with employee counts and filtered by active status.
      security:
        - bearerAuth: []
      parameters:
        - name: include_counts
          in: query
          description: Whether to include employee counts
          schema:
            type: boolean
            default: false
        - name: active
          in: query
          description: Filter by active status
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of sites
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Site'
    post:
      summary: Create a new site
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - site_name
              properties:
                site_name:
                  type: string
                site_code:
                  type: string
      responses:
        '201':
          description: Site created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Site'
        '409':
          description: Site already exists
  /api/sites/{site_id}:
    parameters:
      - name: site_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get a site by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Site details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Site'
        '404':
          description: Site not found
    put:
      summary: Update a site
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site_name:
                  type: string
                site_code:
                  type: string
                is_active:
                  type: boolean
      responses:
        '200':
          description: Site updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Site'
        '404':
          description: Site not found
    delete:
      summary: Delete a site
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Site deleted
        '404':
          description: Site not found
components:
  schemas:
    Site:
      type: object
      properties:
        id:
          type: string
          format: uuid
        site_name:
          type: string
        site_code:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        employee_count:
          type: integer
          description: Included only if requested
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login endpoint
