openapi: 3.1.0
info:
  title: Work Cards API
  version: 1.0.0
  description: API for managing work cards.
paths:
  /api/work_cards:
    get:
      summary: Get work cards
      description: Get work cards in the current business, filtered by site+month or status.
      security:
        - bearerAuth: []
      parameters:
        - name: site_id
          in: query
          description: Filter by site ID (requires month)
          schema:
            type: string
            format: uuid
        - name: month
          in: query
          description: Filter by month (YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: status
          in: query
          description: Filter by review status (NEEDS_REVIEW, APPROVED, etc.)
          schema:
            type: string
      responses:
        '200':
          description: List of work cards
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/WorkCard'
        '400':
          description: Bad Request (e.g. invalid date format)
  /api/work_cards/{card_id}:
    parameters:
      - name: card_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get a work card by ID
      description: Get a specific work card by ID. The work card must belong to the current business.
      security:
        - bearerAuth: []
      parameters:
        - name: details
          in: query
          description: Include nested details (extraction, day_entries, files)
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Work card details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    allOf:
                      - $ref: '#/components/schemas/WorkCard'
                      - type: object
                        properties:
                          extraction:
                            type: object
                            description: Present if details=true
                          day_entries:
                            type: array
                            items:
                              type: object
                            description: Present if details=true
                          files:
                            type: array
                            items:
                              type: object
                            description: Present if details=true
        '404':
          description: Work card not found
    put:
      summary: Update a work card
      description: Update a work card (e.g. assign employee). The work card must belong to the current business.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_id:
                  type: string
                  format: uuid
                  nullable: true
                notes:
                  type: string
      responses:
        '200':
          description: Work card updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/WorkCard'
        '404':
          description: Work card not found
  /api/work_cards/{card_id}/status:
    parameters:
      - name: card_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    put:
      summary: Update review status
      description: Update review status. The work card must belong to the current business.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/WorkCard'
        '404':
          description: Work card not found
  /api/work_cards/{card_id}/approve:
    parameters:
      - name: card_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Approve a work card
      description: Approve a work card. The work card must belong to the current business.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Work card approved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/WorkCard'
        '404':
          description: Work card not found
  /api/work_cards/{card_id}/file:
    parameters:
      - name: card_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get work card image file
      description: Retrieve the image file for a work card. The work card must belong to the current business.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Image file
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Work card or file not found
  /api/work_cards/{card_id}/day-entries:
    parameters:
      - name: card_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get day entries for a work card
      description: Retrieve all day entries (days 1-31) for a work card. The work card must belong to the current business.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of day entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DayEntry'
        '404':
          description: Work card not found
    put:
      summary: Bulk update day entries
      description: Update or create multiple day entries for a work card. The work card must belong to the current business.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - entries
              properties:
                entries:
                  type: array
                  items:
                    type: object
                    required:
                      - day_of_month
                    properties:
                      day_of_month:
                        type: integer
                        minimum: 1
                        maximum: 31
                      from_time:
                        type: string
                        pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$'
                        nullable: true
                      to_time:
                        type: string
                        pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$'
                        nullable: true
                      total_hours:
                        type: number
                        nullable: true
      responses:
        '200':
          description: Day entries updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DayEntry'
        '400':
          description: Validation error
        '404':
          description: Work card not found
  /api/work_cards/upload/single:
    post:
      summary: Upload a single work card
      description: Upload a work card for a known employee. Creates work_card, work_card_file, and work_card_extraction (PENDING).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - site_id
                - employee_id
                - processing_month
                - file
              properties:
                site_id:
                  type: string
                  format: uuid
                employee_id:
                  type: string
                  format: uuid
                processing_month:
                  type: string
                  format: date
                  description: YYYY-MM-DD
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Work card uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/WorkCard'
        '400':
          description: Bad request
  /api/work_cards/upload/batch:
    post:
      summary: Upload multiple work cards (batch)
      description: Upload work cards for unknown employees. Creates work_card (employee_id=NULL), work_card_file, and work_card_extraction (PENDING) for each file.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - site_id
                - processing_month
                - files
              properties:
                site_id:
                  type: string
                  format: uuid
                processing_month:
                  type: string
                  format: date
                  description: YYYY-MM-DD
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '201':
          description: Batch upload completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      uploaded:
                        type: array
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                            work_card_id:
                              type: string
                              format: uuid
                      failed:
                        type: array
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                            error:
                              type: string
                      summary:
                        type: object
                        properties:
                          total:
                            type: integer
                          uploaded:
                            type: integer
                          failed:
                            type: integer
        '400':
          description: Bad request
components:
  schemas:
    WorkCard:
      type: object
      properties:
        id:
          type: string
          format: uuid
        business_id:
          type: string
          format: uuid
        site_id:
          type: string
          format: uuid
        employee_id:
          type: string
          format: uuid
          nullable: true
        processing_month:
          type: string
          format: date
        review_status:
          type: string
          enum: [NEEDS_REVIEW, APPROVED, REJECTED, NEEDS_ASSIGNMENT]
        notes:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    DayEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        work_card_id:
          type: string
          format: uuid
        day_of_month:
          type: integer
          minimum: 1
          maximum: 31
        from_time:
          type: string
          format: time
          nullable: true
        to_time:
          type: string
          format: time
          nullable: true
        total_hours:
          type: number
          nullable: true
        source:
          type: string
          enum: [EXTRACTED, MANUAL]
        is_valid:
          type: boolean
        updated_by_user_id:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login endpoint
