"""make_employee_site_optional

Revision ID: 8866141adb90
Revises: 99576a8b2e7b
Create Date: 2026-02-09 15:17:41.188650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8866141adb90'
down_revision = '99576a8b2e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('site_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('site_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
