"""make_employee_phone_optional

Revision ID: 99576a8b2e7b
Revises: ddcf67c24dc9
Create Date: 2026-02-09 15:14:19.865159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99576a8b2e7b'
down_revision = 'ddcf67c24dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
