"""Initial schema

Revision ID: b8df332d58c2
Revises: 
Create Date: 2026-01-26 12:53:28.943621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8df332d58c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('site_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('passport_id', sa.Text(), nullable=True),
    sa.Column('external_employee_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employees_passport_id', ['passport_id'], unique=True, postgresql_where=sa.text('passport_id IS NOT NULL'))
        batch_op.create_index('ix_employees_site_id', ['site_id'], unique=False)

    op.create_table('export_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processing_month', sa.Date(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('exported_by_user_id', sa.UUID(), nullable=True),
    sa.Column('export_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_file_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_runs', schema=None) as batch_op:
        batch_op.create_index('ix_export_runs_month_site', ['processing_month', 'site_id'], unique=False)

    op.create_table('work_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('processing_month', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_cards', schema=None) as batch_op:
        batch_op.create_index('ix_work_cards_employee_month', ['employee_id', 'processing_month'], unique=False)
        batch_op.create_index('ix_work_cards_review_status', ['review_status'], unique=False)
        batch_op.create_index('ix_work_cards_site_month', ['site_id', 'processing_month'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('work_card_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['work_card_id'], ['work_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_events_site_time', ['site_id', 'created_at'], unique=False)

    op.create_table('work_card_day_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_card_id', sa.UUID(), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('from_time', sa.Time(), nullable=True),
    sa.Column('to_time', sa.Time(), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('day_of_month >= 1 AND day_of_month <= 31', name='check_day_of_month_range'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_card_id'], ['work_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_card_id', 'day_of_month', name='uq_work_card_day_entries_day')
    )
    with op.batch_alter_table('work_card_day_entries', schema=None) as batch_op:
        batch_op.create_index('ix_work_card_day_entries_work_card_id', ['work_card_id'], unique=False)

    op.create_table('work_card_extraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_card_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_employee_name', sa.Text(), nullable=True),
    sa.Column('extracted_passport_id', sa.Text(), nullable=True),
    sa.Column('raw_result_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_result_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_employee_id', sa.UUID(), nullable=True),
    sa.Column('match_method', sa.Text(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matched_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['work_card_id'], ['work_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_card_id')
    )
    with op.batch_alter_table('work_card_extraction', schema=None) as batch_op:
        batch_op.create_index('ix_work_card_extraction_locked_at', ['locked_at'], unique=False)
        batch_op.create_index('ix_work_card_extraction_status', ['status'], unique=False)

    op.create_table('work_card_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_card_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('image_bytes', postgresql.BYTEA(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['work_card_id'], ['work_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_card_files')
    with op.batch_alter_table('work_card_extraction', schema=None) as batch_op:
        batch_op.drop_index('ix_work_card_extraction_status')
        batch_op.drop_index('ix_work_card_extraction_locked_at')

    op.drop_table('work_card_extraction')
    with op.batch_alter_table('work_card_day_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_work_card_day_entries_work_card_id')

    op.drop_table('work_card_day_entries')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_site_time')
        batch_op.drop_index('ix_audit_events_entity')

    op.drop_table('audit_events')
    with op.batch_alter_table('work_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_work_cards_site_month')
        batch_op.drop_index('ix_work_cards_review_status')
        batch_op.drop_index('ix_work_cards_employee_month')

    op.drop_table('work_cards')
    with op.batch_alter_table('export_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_export_runs_month_site')

    op.drop_table('export_runs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_employees_site_id')
        batch_op.drop_index('ix_employees_passport_id', postgresql_where=sa.text('passport_id IS NOT NULL'))

    op.drop_table('employees')
    op.drop_table('users')
    op.drop_table('sites')
    # ### end Alembic commands ###
