"""add_business_name_to_users

Revision ID: be20b2a9c359
Revises: 565101c9853b
Create Date: 2026-01-27 12:49:37.775835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be20b2a9c359'
down_revision = '565101c9853b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_business_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_business_site_time'))
        batch_op.create_index('ix_audit_events_site_time', ['site_id', 'created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_audit_events_business_id'), type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_business_passport'), postgresql_where='(passport_id IS NOT NULL)')
        batch_op.drop_index(batch_op.f('ix_employees_business_site'))
        batch_op.drop_constraint(batch_op.f('fk_employees_business_id'), type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('export_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_runs_business_id'))
        batch_op.drop_index(batch_op.f('ix_export_runs_business_month_site'))
        batch_op.create_index('ix_export_runs_month_site', ['processing_month', 'site_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_export_runs_business_id'), type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_business_id'))
        batch_op.drop_constraint(batch_op.f('fk_users_business_id'), type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('work_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_cards_business_employee_month'))
        batch_op.drop_index(batch_op.f('ix_work_cards_business_id'))
        batch_op.drop_index(batch_op.f('ix_work_cards_business_site_month'))
        batch_op.create_index('ix_work_cards_employee_month', ['employee_id', 'processing_month'], unique=False)
        batch_op.create_index('ix_work_cards_site_month', ['site_id', 'processing_month'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_work_cards_business_id'), type_='foreignkey')
        batch_op.drop_column('business_id')

    op.drop_table('businesses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('business_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('businesses_pkey')),
    sa.UniqueConstraint('business_name', name=op.f('businesses_business_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )

    with op.batch_alter_table('work_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_work_cards_business_id'), 'businesses', ['business_id'], ['id'])
        batch_op.drop_index('ix_work_cards_site_month')
        batch_op.drop_index('ix_work_cards_employee_month')
        batch_op.create_index(batch_op.f('ix_work_cards_business_site_month'), ['business_id', 'site_id', 'processing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_cards_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_cards_business_employee_month'), ['business_id', 'employee_id', 'processing_month'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_users_business_id'), 'businesses', ['business_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_users_business_id'), ['business_id'], unique=False)
        batch_op.drop_column('business_name')

    with op.batch_alter_table('export_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_export_runs_business_id'), 'businesses', ['business_id'], ['id'])
        batch_op.drop_index('ix_export_runs_month_site')
        batch_op.create_index(batch_op.f('ix_export_runs_business_month_site'), ['business_id', 'processing_month', 'site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_runs_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_employees_business_id'), 'businesses', ['business_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_employees_business_site'), ['business_id', 'site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_business_passport'), ['business_id', 'passport_id'], unique=False, postgresql_where='(passport_id IS NOT NULL)')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_audit_events_business_id'), 'businesses', ['business_id'], ['id'])
        batch_op.drop_index('ix_audit_events_site_time')
        batch_op.create_index(batch_op.f('ix_audit_events_business_site_time'), ['business_id', 'site_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###
