"""add_phone_number_to_employees

Revision ID: d3949289fe3b
Revises: c1a2b3d4e5f6
Create Date: 2026-01-28 09:30:27.568420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3949289fe3b'
down_revision = 'c1a2b3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Text(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE employees SET phone_number = '' WHERE phone_number IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('phone_number', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
